### PR TITLE
Windows compatibility

### PR DESCRIPTION
**Pull request by mikex86**
Adding Windows compatibility by using a different file name delimiter.

Uses the old delimiter when not on Windows to preserve backwards compatibility.

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
LGTM. Tested and it works fine with Precise. @forslund Feel free to merge if it looks good to you.

**Comment by forslund** [comment]
Hi @GommeAntiLegit we like the contributors to sign a Contributor License Agreement before merging pull requests.

This is to protect yourself, the project, and users of Mycroft technologies. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.
 
Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by mikex86** [comment]
I have signed the agreement.

**Comment by mikex86** [comment]
Since @MatthewScholefield has stated that the PR looks good to him, I hope that merging might be considered, now that the CLA is signed. @forslund

**Comment by forslund** [comment]
Yes, merging! Thanks

**Pull request merged**
